### ISSUE TITLE
Network Recolor Runs out of Memory

### ISSUE THREAD

**Issue by RishiDesai** [wjrl/BioFabric#100]
After loading SCerevisae.gw, and then changing the darken link level by .01, the loop reporter stalls at Generating Full Network at around 100% for a few seconds and then gives a Out of Memory exception. This happens even when there is nothing to change (e.g. when I call recolor for minimum drain zone change but I haven't implemented the actual drain zone pruning).

**Comment by wjrl** [comment]
On recolor only, was building quad tree to a depth of 13 levels (67 million bins). Fixed.
