### ISSUE TITLE
Order targets by degree ignores link tags

### ISSUE THREAD

**Issue by wlongabaugh** [wjrl/BioFabric#81]
It appears that the controlTopLayout.targetMode: ctrlTop.degreeOdometer setting lays out some higher-degree targets among lower degree runs (e.g. 3-degree nodes appear in the 2-degree run) if a target has multiple links from the same source (only edge labels are different).

**Comment by wjrl** [comment]
This is due to degree calculator counting the number of neighbor nodes instead of counting number of links. Fixed.
