### ISSUE TITLE
Large SIF files fail to load

### ISSUE THREAD

**Issue by wjrl** [wjrl/BioFabric#94]
SIF files greater than 500000 characters are not loading (e.g. SCFail.sif)

**Comment by RishiDesai** [comment]
I accidentally left a return (true) when big files load and didnt' catch it because I didn't have any large enough files to test it with.

**Comment by wjrl** [comment]
Could you issue a pull request with the fix in it?

**Comment by RishiDesai** [comment]
Fixed in 6b5d29b39c83635f37aae719422e6b493991a1fa and just sent a request.
